name: chirp
description: The best logger of 2026. Format log messages like Widgets
version: 0.5.0
repository: https://github.com/passsy/chirp

environment:
  sdk: ^3.0.0

dependencies:
  clock: ^1.0.0

dev_dependencies:
  lint: ^2.8.0
  test: ^1.25.6
