name: chirp
description: >-
  A lightweight, fully customizable Dart logger with automatic caller info, zero      
    config, rotating file writers, and structured logging.
version: 0.8.0
repository: https://github.com/passsy/chirp
topics:
  - logging
  - ansi
  - error

environment:
  sdk: ^3.0.0

dependencies:
  clock: ^1.1.0
  meta: ^1.11.0
  synchronized: ^3.0.0

sidekick:
  puro:
    useDartSdk: '3.10.1'

dev_dependencies:
  fake_async: ^1.3.0
  lint: ^2.0.0
  test: ^1.24.0
