name: print_limits
description: "A test project for print limits"
publish_to: 'none'
version: 1.0.0+1

environment:
  flutter: '^3.38.3'
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  chirp:
  cupertino_icons: ^1.0.8

dependency_overrides:
  chirp:
    path: ../../packages/chirp

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.8.0

flutter:
  uses-material-design: true
