name: simple_example
description: Simple example demonstrating chirp logging works out of the box

environment:
  sdk: ^3.0.0

dependencies:
  chirp:
    path: ../../packages/chirp
dev_dependencies:
  lint: ^2.8.0
