name: Nightly

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'

jobs:
  stable:
    runs-on: ubuntu-latest
    container:
      image: dart:stable
    steps:
      - uses: actions/checkout@v4
      - name: Dart version
        run: dart --version

      # Test chirp_protocol
      - name: Download dependencies (chirp_protocol)
        run: dart pub get
        working-directory: packages/chirp_protocol
      - name: Test (chirp_protocol)
        run: dart test
        working-directory: packages/chirp_protocol

      # Test chirp
      - name: Download dependencies (chirp)
        run: dart pub get
        working-directory: packages/chirp
      - name: Test (chirp)
        run: dart test
        working-directory: packages/chirp

  beta:
    runs-on: ubuntu-latest
    container:
      image: dart:beta
    steps:
      - uses: actions/checkout@v4
      - name: Dart version
        run: dart --version

      # Test chirp_protocol
      - name: Download dependencies (chirp_protocol)
        run: dart pub get
        working-directory: packages/chirp_protocol
      - name: Test (chirp_protocol)
        run: dart test
        working-directory: packages/chirp_protocol

      # Test chirp
      - name: Download dependencies (chirp)
        run: dart pub get
        working-directory: packages/chirp
      - name: Test (chirp)
        run: dart test
        working-directory: packages/chirp
